services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    networks:
      - spring-cloud-network

  mock-oauth2-server:
    image: 'ghcr.io/navikt/mock-oauth2-server:2.1.5'
    restart: on-failure
    ports:
      - "8180:8180"
    volumes:
      - ./oauth_mock/config.json:/app/config.json
    hostname: host.docker.internal
    environment:
      LOG_LEVEL: "debug"
      SERVER_PORT: 8180
      JSON_CONFIG_PATH: /app/config.json

  issuer-mgmt-service:
    container_name: verifier-mgmt-service
    build:
      context: .
      dockerfile: Dockerfile
    image: verifier-mgmt-service:latest
    ports:
      - 8002:8080
    networks:
      - spring-cloud-network
    environment:
      MOCK_ISSUER_URL: "mock-oauth2-server:8080"

networks:
  spring-cloud-network:
    driver: bridge