services:
  redis:
    image: 'redis:latest'
    network_mode: host
    ports:
      - "6379:6379"

  issuer-mgmt-service:
    container_name: verifier-mgmt-service
    build:
      context: .
      dockerfile: Dockerfile
    image: verifier-mgmt-service:latest
    ports:
      - "8002:8002"
    environment:
      REDIS_URL: localhost
      REDIS_PORT: 6379
    depends_on:
      - redis
    network_mode: host