services:
  redis:
    image: 'redis:latest'
    network_mode: host
    ports:
      - "6379:6379"

  mock-oauth2-server:
    image: "ghcr.io/navikt/mock-oauth2-server:2.1.5"
    restart: on-failure
    ports:
      - "8180:8180"
    volumes:
      - ./oauth_mock/config.json:/app/config.json
    environment:
      LOG_LEVEL: "debug"
      SERVER_PORT: 8180
      JSON_CONFIG_PATH: /app/config.json
    network_mode: host

  issuer-mgmt-service:
    container_name: verifier-mgmt-service
    build:
      context: .
      dockerfile: Dockerfile
    image: verifier-mgmt-service:latest
    ports:
      - "8002:8002"
    environment:
      REDIS_URL: localhost
      REDIS_PORT: 6379
    depends_on:
      - redis
      - mock-oauth2-server
    network_mode: host