# SPDX-FileCopyrightText: 2025 Swiss Confederation
#
# SPDX-License-Identifier: MIT

services:
  postgres:
    image: postgres:15.8
    environment:
      POSTGRES_USER: "verifier_mgmt_user"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "verifier_db"
    ports:
      - '5434:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U verifier_mgmt_user -d verifier_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
  verifier-agent-management:
    image: ghcr.io/e-id-admin/eidch-verifier-agent-management:latest
    environment:
      OID4VP_URL: "<url of your verifier-agent-oid4vp service>"
      # Persistence
      POSTGRES_USER: "verifier_mgmt_user"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "verifier_db"
      POSTGRES_JDBC: "jdbc:postgresql://postgres:5432/verifier_db"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  verifier-agent-oid4vp:
    image: ghcr.io/e-id-admin/eidch-verifier-agent-oid4vp:latest
    configs:
      - source: verifier_metadata
        target: /verifier_metadata.json
    ports:
      - "8081:8080"
    environment:
      EXTERNAL_URL: "https://<external url of this service>"
      OPENID_CLIENT_METADATA_FILE: "file:/verifier_metadata.json"
      VERIFIER_DID: "<Your VERIFIER_DID>"
      DID_VERIFICATION_METHOD: "<Your VERIFIER_DID>#assert-key-01"
      VERIFIER_NAME: "<Your verifier name>"
      SIGNING_KEY: |
        -----BEGIN EC PRIVATE KEY-----
        <private key of the file "assert-key-01">
        -----END EC PRIVATE KEY-----
      # Persistence
      POSTGRES_USER: "verifier_mgmt_user"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "verifier_db"
      POSTGRES_JDBC: "jdbc:postgresql://postgres:5432/verifier_db"

configs:
  verifier_metadata:
    content: |
      {
        "client_id": "${CLIENT_ID}",
        "client_name#en": "Development Demo Verifier",
        "client_name#fr": "Vérificateur de démonstration de développement",
        "client_name#de-DE": "Entwicklungs-Demo-Verifizierer",
        "client_name#de-CH": "Entwickligs-Demo-Verifizier",
        "client_name#de": "Entwicklungs-Demo-Verifizierer (Fallback DE)",
        "client_name": "DEV Demo Verifier (Base)",
        "logo_uri": "www.example.com/logo.png",
        "logo_uri#fr": "www.example.com/logo_fr.png"
      }
