# SPDX-FileCopyrightText: 2025 Swiss Confederation
#
# SPDX-License-Identifier: MIT

services:
  verifier_postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "verifier_user"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "verifier_db"
    ports:
      - "5434:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U verifier_user -d verifier_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
  verifier-service:
    image: ghcr.io/swiyu-admin-ch/swiyu-verifier:latest
    configs:
      - source: verifier_metadata
        target: /verifier_metadata.json
    ports:
      - "8083:8080"
    environment:
      EXTERNAL_URL: ${EXTERNAL_URL}
      OPENID_CLIENT_METADATA_FILE: file:/verifier_metadata.json
      VERIFIER_DID: ${VERIFIER_DID}
      DID_VERIFICATION_METHOD: ${DID_VERIFICATION_METHOD}
      SIGNING_KEY: ${SIGNING_KEY}

      # Persistence
      POSTGRES_USER: "verifier_user"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "verifier_db"
      POSTGRES_JDBC: "jdbc:postgresql://verifier_postgres:5432/verifier_db"

configs:
  verifier_metadata:
    # Verifier logo configuration guide: https://swiyu-admin-ch.github.io/cookbooks/vc-visual-presentation/#verifier-logo
    content: |
      {
        "client_id": "${VERIFIER_DID}",
        "client_name#en": "Development Demo Verifier",
        "client_name#fr": "Vérificateur de démonstration de développement",
        "client_name#de-DE": "Entwicklungs-Demo-Verifizierer",
        "client_name#de-CH": "Entwickligs-Demo-Verifizier",
        "client_name#de": "Entwicklungs-Demo-Verifizierer (Fallback DE)",
        "client_name": "DEV Demo Verifier (Base)",
        "logo_uri": "www.example.com/logo.png",
        "logo_uri#fr": "www.example.com/logo_fr.png",
        "vp_formats": {
          "jwt_vp": {
            "alg": [
              "ES256"
            ]
          }
        }
      }