spring:
  application:
    name: verifier-management
  data:
    redis:
      database: 0
      host: redis
      port: 6379
      timeout: 60000
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          authorization-uri: "http://host.docker.internal:8180/issuer1/mock_issuer"
#          issuer-uri: "http://host.docker.internal:8180/mock_issuer"
#          jwk-set-uri: "http://host.docker.internal:8180/mock_issuer/jwks"

application:
  oid4vp-url: http://localhost:8003

logging:
  level:
    root: debug
