server:
  port: 8003

spring:
  docker:
    compose:
      enabled: false
  datasource:
    url: "jdbc:postgresql://localhost:5434/verifier_db"
    username: "verifier_mgmt_user"
    password: "secret"
    driver-class-name: org.postgresql.Driver

