# SPDX-FileCopyrightText: 2025 Swiss Confederation
#
# SPDX-License-Identifier: MIT

# For usage of this file please refer to the README.md#Integrated_service_development
server:
  port: 8002

application:
  oid4vp-url: "${OID4VP_URL:http://localhost:8003}"
