spring:
  docker:
    compose:
      enabled: false
  data:
    redis:
      database: 0
      host: redis
      port: 6379
      timeout: 60000
application:
  external-url: "${EXTERNAL_URL}"
  "client_id": "${VERIFIER_DID}"
  "client_id_scheme": "did"
  client_name: "${VERIFIER_NAME}"
  logo_uri: "${VERIFIER_LOGO}"